const automations = [
  {name:'Auto Grid Maker',code:'GRID',label:'Field data cleanup',categories:['cad','data'],summary:'Daily survey point files often mix multiple days and duplicate points, which slows setup of treatment grids—map areas that show which pieces of ground have been treated—and risks bad drawing inputs. This tool automatically keeps only the points for a chosen day, removes duplicates, and produces one clean file. That gives CAD a reliable starting point without manual cleanup.',meta:'AutoCAD scripting · Spreadsheet files'},
  {name:'Custom Grid Maker',code:'AREA',label:'Treatment area layout',categories:['cad'],summary:'Drawing treatment grids—map areas that show which pieces of ground have been treated—by hand is slow and easy to misalign when size and placement have to stay consistent. This tool automatically builds a rectangular treatment grid to a size you choose from two points you pick in the drawing. That keeps treated-area maps consistent and cuts repetitive drafting time.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'EOD Grid Change',code:'EOD',label:'End-of-day drawing update',categories:['cad'],summary:'At the end of the day, treatment grids that already have survey points still have to be moved into the next production status by hand, which is easy to miss and can make treated-ground progress look outdated. This tool finds those grids automatically and advances them to the correct status. That keeps treated-area drawings current without a tedious status-by-status check.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'Grid Duplicate Cleanup',code:'DUPE',label:'Drawing quality check',categories:['cad'],summary:'Duplicate treatment grids on a drawing make treated-ground progress hard to trust and can throw off area counts. This tool finds and removes those duplicate outlines, even when they sit on different layers. That keeps the treated-area map clean and the quantities reliable.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Grid Label Duplicate Checker',code:'QA',label:'Label quality check',categories:['cad'],summary:'Repeated labels on treatment grids make it unclear which treated ground area is which and can cause drawings to fail review. This tool finds duplicate grid labels before a drawing is submitted. That catches naming mistakes early instead of during a last-minute check.',meta:'AutoCAD scripting · Drawing text'},
  {name:'Grid Automation Notebook',code:'BATCH',label:'CAD data automation',categories:['cad','data'],summary:'Runs repeatable batch grid operations from CSV inputs in a reviewable notebook workflow.',meta:'Python · Jupyter · CSV'},
  {name:'OCR Material & Item Tool',code:'ITEM',label:'Document OCR counting',categories:['cad','ai'],summary:'Counting materials or items from images, PDFs, drawings, specs, and plans by hand is slow and easy to miss on busy pages. This tool uses OCR to read those visuals and automatically tally the materials or items shown. That turns a manual count into a faster, repeatable check across the documents you already use.',meta:'Python · OCR · Image analysis'},
  {name:'Hyperlink Grid Labeler',code:'LINK',label:'Treatment-grid labeling',categories:['cad'],summary:'Treatment grids often already carry their IDs as hidden hyperlinks, but writing those IDs as visible labels by hand is slow and easy to mismatch. This tool reads each grid’s hyperlink and automatically places a centered label from it. That keeps treated-area names consistent without retyping every ID.',meta:'AutoCAD scripting · Drawing text'},
  {name:'Layer List',code:'LAYR',label:'Drawing layer inventory',categories:['cad','utility'],summary:'Checking which layers a drawing uses usually means opening layer menus and scanning by hand, which slows standards reviews. This tool automatically lists every layer in the drawing. That makes it faster to spot missing standards, clutter, or setup problems.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Layer Maker',code:'MAKE',label:'Drawing layer setup',categories:['cad'],summary:'Setting up dozens of drawing layers by hand is repetitive and easy to get inconsistent from file to file. This tool reads a reusable layer list and creates a whole batch of layers quickly and accurately in one pass. That standardizes setup and removes the click-by-click layer building.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Layout Generator',code:'LAY',label:'Print sheet setup',categories:['cad'],summary:'Creating print layouts one by one—and setting which layers show in each view—takes a lot of repetitive clicking and is easy to set up inconsistently. This tool builds the named layouts from a reusable definition and applies the viewport layer settings automatically. That gets sheets print-ready faster with the same visibility rules every time.',meta:'AutoCAD scripting · Print layouts'},
  {name:'Auto Labeler',code:'LBL',label:'Sequential point labeling',categories:['cad'],summary:'Numbering points on a drawing by hand is slow and easy to break the sequence when you skip or restart. This tool places sequential two-line labels at the points you select. That keeps IDs in order and cuts the retyping.',meta:'AutoCAD scripting · Drawing text'},
  {name:'Turnover Automation',code:'TURN',label:'End-of-day turnover package',categories:['cad'],summary:'Closing out the day usually means creating turnover fills, setting up work-package layers, and matching survey points to those packages by hand—several steps that are easy to leave incomplete. This tool builds those turnover fills and work-package layers and links each point to its package in one end-of-day run. That finishes turnover prep faster and with fewer missed connections.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'DAR Area Export',code:'AREA',label:'Daily report area export',categories:['cad','reporting'],summary:'Pulling treated-area sizes out of drawings for the daily activity report (DAR) usually means measuring shapes by hand and retyping numbers into a spreadsheet. This tool calculates the labeled areas and exports clean spreadsheet records ready for that report. That gets accurate area totals into the DAR faster and with fewer typing mistakes.',meta:'AutoCAD scripting · Spreadsheet files'},
  {name:'Treated Grid Center Export',code:'CTR',label:'QA/QC center-point export',categories:['cad','data'],summary:'Checking treated grids for QA/QC often needs each grid’s geometric center, and finding those points by hand is slow and easy to misplace. This tool exports the center of each treated grid into a clean spreadsheet for tracking and review. That gives QA/QC a reliable center point for every treated area without manual measuring.',meta:'AutoCAD scripting · Spreadsheet files'},
  {name:'DAR Draw-Order Cleanup',code:'ORDER',label:'Completed-grid display cleanup',categories:['cad'],summary:'Completed treatment grids can sit behind other drawing content, which makes daily reporting views hard to read. This tool brings those completed grids to the front for reporting without changing their shape or size. That keeps the daily report view clear while leaving the geometry untouched.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'DAR Volume Calculator',code:'VOL',label:'Daily report volume calculation',categories:['cad','data','reporting'],summary:'Daily reports need treated material volumes, but pairing each area with its depth by hand is slow and easy to miscalculate. This tool matches each treated-area shape with its depth label and calculates report-ready volumes automatically. That gets accurate quantities into the daily activity report without spreadsheet gymnastics.',meta:'AutoCAD scripting · Quantity takeoff'},
  {name:'AutoCAD Point Extract',code:'PTS',label:'Drawing point export',categories:['cad','data'],summary:'Copying point coordinates and attributes out of a drawing by hand is slow and invites typos. This tool exports the points from the active drawing—coordinates and their attributes—into a usable file. That gives field and office teams a clean point list without retyping.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Area / Takeoff Calculator',code:'QTY',label:'Area takeoff by layer',categories:['cad','data'],summary:'Measuring areas across many layers and regrouping them by work package for takeoff is tedious and easy to mis-total. This tool calculates polygon areas by layer and can export the results as a spreadsheet, including totals grouped by work package. That produces cleaner quantity takeoffs with less manual sorting.',meta:'AutoCAD scripting · Spreadsheet files · Work packages'},
  {name:'Hatch Boundary Extractor',code:'HATCH',label:'Filled-area boundary export',categories:['cad','data'],summary:'Filled areas in a drawing don’t always give you an easy outline to measure or check, so recovering their edges by hand is slow. This tool pulls the boundary corner points from those filled areas into usable coordinates. That supports analysis and QA without redrawing the outlines manually.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'MTEXT CSV Exporter',code:'TEXT',label:'Drawing text export',categories:['cad','data'],summary:'Copying multiline text off a drawing layer into a spreadsheet by hand is slow and messy. This tool pulls cleaned text from a selected layer and exports it to a spreadsheet file. That turns drawing notes and labels into usable records without retyping.',meta:'AutoCAD scripting · Drawing text · Spreadsheet files'},
  {name:'KML Generator',code:'KML',label:'Map file export',categories:['cad','data'],summary:'Site polygons drawn in Louisiana State Plane coordinates won’t open correctly in common map tools until they’re converted. This tool converts those shapes into standard map coordinates and exports a KML file. That lets you view the same areas in Google Earth and other map apps without manual coordinate math.',meta:'AutoCAD scripting · Map coordinates · KML'},
  {name:'Point-to-Hatch Classifier',code:'CLASS',label:'Point-in-area classification',categories:['cad','data'],summary:'Figuring out which filled area contains each survey or drawing point is slow when you check them one by one. This tool matches every point to the filled region that contains it and produces a structured classification list. That turns a manual spatial check into a repeatable point-to-area assignment.',meta:'Python · Reviewable notebook · Geometry'},
  {name:'Polyline-to-Table',code:'TABLE',label:'Outline-to-table conversion',categories:['cad','data'],summary:'Typing every corner of a drawn outline into a table by hand is slow and easy to mistype on long shapes. This tool turns those outline corner points into an AutoCAD table automatically, and can run larger batches from outside the drawing when needed. That documents geometry as a clean table without retyping coordinates.',meta:'AutoCAD scripting · Python · Batch control'},
  {name:'Coordinate Picker',code:'XY',label:'Precise coordinate readout',categories:['cad','utility'],summary:'Reading exact X and Y values from a drawing point usually means digging through properties or status readouts. This tool returns the precise coordinates for a point you select. That makes quick location checks faster when you need exact numbers.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'EOD Cleanup',code:'CLEAN',label:'End-of-day drawing cleanup',categories:['cad'],summary:'End-of-day drawings often still hold temporary survey points and treatment grids that haven’t been marked complete, which leaves the file messy for the next shift. This tool removes those temporary survey points and advances production grids to their completed state. That closes the day with a cleaner, status-correct drawing.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'EOD Complete',code:'DONE',label:'One-command end-of-day closeout',categories:['cad'],summary:'Running grid status updates and drawing cleanup as separate end-of-day steps takes extra time and is easy to finish only halfway. This tool chains treatment-grid promotion and cleanup into one repeatable command. That closes the day in a single pass instead of juggling multiple routines.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'Site Map Draw-Order Cleanup',code:'MAP',label:'Site-map display cleanup',categories:['cad'],summary:'Treatment grids can cover up site-map details and make the overall drawing harder to read. This tool sends those grid layers behind the site-map content automatically. That keeps the map presentation consistent without manually restacking every layer.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Stray Polyline Finder',code:'OPEN',label:'Open-outline quality check',categories:['cad'],summary:'Outlines that aren’t fully closed can break area calculations and treated-grid workflows, and they’re easy to miss on a busy drawing. This tool finds and counts those open outlines so you know what still needs fixing. That catches geometry problems before they show up in quantities or reports.',meta:'AutoCAD scripting · Quality check'},
  {name:'Completed Grid QA Check',code:'CHECK',label:'Completed-grid verification list',categories:['cad'],summary:'Before turnover, someone still has to confirm which treatment grids are marked complete, and hunting through the drawing by eye is easy to miss. This tool builds a verification list of grids marked complete. That gives a clear pre-turnover check instead of a visual scan.',meta:'AutoCAD scripting · Quality check'},
  {name:'AutoLISP Unloader',code:'UNLOAD',label:'Command cleanup utility',categories:['cad','utility'],summary:'Custom AutoCAD commands can stick around after testing and clutter the session until you restart the whole program. This tool unloads those user-defined commands without restarting AutoCAD. That lets you refresh tools quickly while you develop and test.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Inward Offset',code:'INSET',label:'Inward outline offset',categories:['cad'],summary:'Offsetting many closed outlines inward one by one is slow, and a normal offset can jump the wrong direction. This tool offsets multiple closed outlines strictly toward their interiors in one run. That creates consistent inset shapes without babysitting each offset.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'XREF Reload All',code:'XREF',label:'Reference refresh utility',categories:['cad','utility'],summary:'When attached reference drawings change, reloading them one at a time is tedious and easy to leave partially stale. This tool reloads every attached external reference with a single command. That refreshes the full drawing set without a click-by-click reload.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'Clifty Creek Master Workbook Updater',code:'BOOK',label:'Master workbook update',categories:['data','reporting'],summary:'Keeping a master project workbook current usually means copying fresh source data by hand and risking overwritten or mismatched rows. This tool replaces or key-updates a target workbook sheet from spreadsheet source files automatically. That keeps the Clifty Creek master book aligned with the latest inputs.',meta:'Python · Excel · Spreadsheet files'},
  {name:'Daily Point CSV Processor',code:'CSV',label:'Daily survey file cleanup',categories:['data','field'],summary:'Daily survey point files often mix dates and duplicate rows, which slows end-of-day processing. This desktop tool filters rows by date, removes duplicates, and merges the cleaned results for the day’s closeout. That prepares field point data for CAD without manual spreadsheet cleanup.',meta:'Python · Desktop app · Spreadsheet files'},
  {name:'DXF Fast Takeoff',code:'DXF',label:'Fast DXF quantity takeoff',categories:['cad','data'],summary:'Counting and measuring filled areas inside selected boundaries is slow when you do it visually in a drawing export. This tool counts and measures those filled areas within chosen DXF boundary regions automatically. That produces faster quantity takeoffs from drawing files.',meta:'Python · DXF files'},
  {name:'Live AutoCAD MTEXT Extractor',code:'LIVE',label:'Live drawing text extract',categories:['cad','data'],summary:'Pulling large batches of drawing text out of an open AutoCAD session by hand is slow and interruptive. This tool controls a running AutoCAD session and extracts multiline text in batches. That moves drawing labels into usable data without retyping from the screen.',meta:'Python · Live AutoCAD control'},
  {name:'MTEXT Workbook Sorter',code:'SORT',label:'Drawing-label workbook organizer',categories:['data','reporting'],summary:'Extracted drawing labels often land in one messy list that still has to be sorted into useful categories by hand. This tool organizes those labels into categorized, multi-sheet Excel workbooks. That turns raw text exports into structured records ready for review.',meta:'Python · Excel'},
  {name:'Polygon Partitioner',code:'SPLIT',label:'Area split into sub-polygons',categories:['cad'],summary:'Dividing a large work area into practical smaller polygons by hand takes time and can produce uneven pieces. This tool splits a selected AutoCAD polygon into usable sub-polygons through an external controller. That creates workable area pieces faster and more consistently.',meta:'Python · Live AutoCAD control'},
  {name:'Trimble TSC7 Data Puller',code:'TSC7',label:'Survey collector data pull',categories:['field','data'],summary:'Getting survey data off a field collector usually means picking work orders, preserving raw files, and cleaning outputs through several manual steps. This tool selects the work orders, keeps the raw survey files safe, cleans the data, and creates dated outputs. That shortens the path from collector to usable office files.',meta:'Python · Desktop app'},
  {name:'CAT VisionLink Fault Report Pipeline',code:'CAT',label:'Equipment fault reporting',categories:['reporting','data'],summary:'Equipment fault exports from VisionLink arrive messy and still need to become readable fault-code and seatbelt reports. This tool cleans those exports and produces formatted PDF reports automatically. That turns raw machine alerts into documents supervisors can review quickly.',meta:'Python · Browser automation · PDF',status:'In development'},
  {name:'DAR Field Reporting App',code:'DAR',label:'Mobile daily activity report',categories:['field','apps','reporting'],summary:'Building a daily activity report across people, hours, equipment, areas, notes, and email delivery usually spans several tools and late-night rework. This mobile app captures all of that in one field workflow, including review and delivery. That gets the DAR from the jobsite to the office without stitching systems together by hand.',meta:'Power Apps · Outlook'},
  {name:'Load Count Log',code:'LOAD',label:'Material haul logging',categories:['field','apps'],summary:'Tracking daily material hauls on paper or ad-hoc notes makes load counts hard to submit and harder to audit later. This field app structures load entries for fast submission and tracking. That gives crews a simple place to log hauls as the work happens.',meta:'Power Apps · SharePoint'},
  {name:'DAR Email-to-Workbook Pipeline',code:'FILL',label:'Email-to-DAR workbook fill',categories:['reporting','data','ai'],summary:'Turning manager DAR emails into filled workbooks, photo logs, and run records is repetitive and easy to word inconsistently. This tool extracts structured content from those emails, reviews wording with a local AI model, fills the Excel logs and photos, and records each run. That produces daily report workbooks with less copy-paste and more consistent language.',meta:'Python · Outlook · Excel · Local AI'},
  {name:'QA/QC Elevation Workbooks',code:'QAQC',label:'Survey-versus-design QA workbooks',categories:['reporting','data','field'],summary:'Comparing daily survey elevations to design, checking tolerances, and spotting duplicates usually means rebuilding the same workbook from scratch. This tool builds those survey-versus-design workbooks with tolerances, duplicate checks, dashboards, and exports. That gives QA/QC a ready daily package instead of a manual rebuild.',meta:'Python · Excel · Survey data'},
  {name:'PDF Compressor',code:'PDF',label:'PDF size reduction',categories:['utility','reporting'],summary:'Large PDFs are hard to email or archive, but aggressive compression can ruin transparent images. This desktop tool reduces PDF sizes with email and print presets while protecting transparent imagery. That makes documents easier to share without wrecking the visuals.',meta:'Python · Windows desktop'},
  {name:'Outlook Daily Summary',code:'MAIL',label:'Daily email digest and actions',categories:['reporting','ai'],summary:'A busy Outlook inbox buries the actions that actually matter for the day’s work. This tool builds focused email digests, extracts categorized action items, and routes them into local work notes. That turns inbox noise into a clearer daily action list.',meta:'Python · Outlook · Local notes',status:'In development'},
  {name:'Receipt Parser & Expense Grouper',code:'EXP',label:'Receipt-to-expense reports',categories:['data','reporting'],summary:'Sorting receipts by vendor, date, amount, and payment card for expense reports is slow and easy to misfile. This tool reads those details from receipt files and creates Excel reports grouped by card. That prepares expense packages without manual receipt transcription.',meta:'Python · PDF · Excel'},
  {name:'Receipt / Ticket OCR Renamer',code:'OCR',label:'Scanned ticket OCR renaming',categories:['data','ai','utility'],summary:'Scanned receipt and ticket PDFs often arrive as one unlabeled file that still has to be split and renamed by hand. This tool splits those scans, reads dates and totals with OCR, and applies consistent page names. That turns a messy scan stack into clearly named documents.',meta:'Python · OCR · PDF'},
  {name:'Fuel Ticket Scanner',code:'FUEL',label:'Fuel ticket data extract',categories:['field','data'],summary:'Fuel tickets hold flags, ticket numbers, and gallon quantities that usually get retyped from PDFs into tracking sheets. This tool extracts those fields from fuel-ticket PDFs automatically. That captures fuel use for field records without manual ticket transcription.',meta:'Python · OCR · PDF'},
  {name:'Phase Code Workbook Splitter',code:'PHASE',label:'Phase-code workbook split',categories:['data','reporting'],summary:'Payroll or job-cost files often need a separate formatted sheet for every phase code, which is tedious to build manually. This tool turns a cost spreadsheet into a formatted Excel tab for each phase code. That organizes job-cost data the way accounting and field teams review it.',meta:'Python · Spreadsheet files · Excel'},
  {name:'Local Whisper Dictation',code:'VOICE',label:'Offline speech-to-text',categories:['ai','utility'],summary:'Typing long notes, emails, or field write-ups breaks focus, especially when you want the work to stay on your machine. This tool provides offline speech-to-text with a global hotkey and can type or copy the result automatically. That turns spoken notes into text without sending audio to the cloud.',meta:'Python · Local speech AI · GPU'},
  {name:'Optimal Work Dashboard',code:'FOCUS',label:'Personal focus dashboard',categories:['apps'],summary:'Tasks, checklists, timers, and end-of-day reflection often live in separate apps, which makes it hard to stay focused. This local desktop dashboard combines those pieces in one place. That keeps personal work planning and focus sessions in a single private tool.',meta:'Desktop app · Local database'},
  {name:'AutoCAD LISP Test Harness',code:'TEST',label:'CAD script test harness',categories:['cad','utility'],summary:'Testing custom AutoCAD scripts usually means loading them by hand, watching for errors, and repeating the same checks every time something changes. This tool loads and runs those scripts in Civil 3D, captures errors and logs, and evaluates reusable test cards. That makes automation development safer and faster to verify.',meta:'Python · Civil 3D · Test cards'},
  {name:'ENTACT Civil 3D Assistant',code:'C3D',label:'Local AI drafting assistant',categories:['cad','ai','apps'],summary:'Complex Civil 3D drafting steps are hard to repeat consistently, and unchecked AI actions in CAD are risky. This assistant plans drafting actions through a local model, asks for confirmation, and keeps auditable execution logs. That speeds routine CAD work while keeping a human in control of what actually runs.',meta:'C# · .NET · Civil 3D · Local AI'},
  {name:'MasterFlow Cut / Fill Heat Map',code:'HEAT',label:'Cut/fill heat-map builder',categories:['cad','data'],summary:'Building a cut/fill color map usually means importing surfaces, setting a boundary, creating a volume surface, and styling bands through several manual Civil 3D steps. This tool runs that whole sequence in one command from LandXML surfaces and a boundary. That produces a clear cut/fill heat map without the multi-step setup.',meta:'C# · Civil 3D · LandXML'},
  {name:'Panel Layout Generator',code:'PANEL',label:'Panel outline builder',categories:['cad'],summary:'Grouping named layout points into closed panel outlines and labels by hand is repetitive and easy to mismatch. This tool builds those closed panel shapes with centered labels automatically. That turns scattered layout points into consistent panel geometry.',meta:'Python · AutoCAD'},
  {name:'Panel Vertex Extractor',code:'VERT',label:'Panel corner export',categories:['cad','data'],summary:'Exporting every labeled panel’s corner points with consistent names is slow when done one shape at a time. This tool scans closed labeled panels and exports their vertices to a spreadsheet with consistent naming. That gives downstream workflows a clean panel-corner file.',meta:'Python · DXF · AutoCAD scripting'},
  {name:'Surface Elevation Corrector',code:'ELEV',label:'Surface elevation sampling',categories:['cad','data'],summary:'Getting corrected elevations for a point list from a design surface usually means sampling locations carefully without disturbing the source points. This tool samples each point against a TIN surface and exports the corrected elevations while leaving the originals untouched. That produces elevation checks without rewriting the field point set.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'MTEXT Grid Maker',code:'MTXT',label:'Name-list text grid',categories:['cad'],summary:'Placing a fixed list of names as evenly spaced drawing text is tedious to align by hand. This tool lays that name list out as a square grid of text automatically. That creates a clean labeled grid without manual spacing.',meta:'AutoCAD scripting · Drawing text'},
  {name:'Hermes DAR Controller',code:'MERGE',label:'Multi-manager DAR merge',categories:['reporting','data'],summary:'When several managers send daily report emails, merging them into one approved DAR without changing the template is slow and conflict-prone. This tool imports those emails, merges the content, flags conflicts, and builds an approved DAR from the unchanged template. That consolidates manager inputs into one controlled daily report.',meta:'Excel macros · Python · Email files'},
  {name:'Excel DAR RowHider',code:'ROWS',label:'Daily-report row cleanup',categories:['reporting','data'],summary:'Daily report workbooks often show long stretches of empty rows that make printing and review harder. This tool hides unused rows and restores them automatically when content is added. That keeps the DAR compact without losing room for new entries.',meta:'Excel macros · PowerShell'},
  {name:'Universal Grid Leader Maker',code:'LEAD',label:'Treatment-grid leader labeling',categories:['cad'],summary:'Matching labels to closed repair grids and building callout leaders by hand is slow and easy to leave incomplete. This tool matches labels to those grids, creates native multileader callouts, and produces QA reports. That labels treated-area grids consistently and shows what still needs review.',meta:'AutoCAD scripting · Python · DXF'},
  {name:'MLeader Text Point Exporter',code:'MLEAD',label:'Leader text and point export',categories:['cad','data'],summary:'Survey and CAD teams often need both the callout text and the exact arrow-point location from multileaders, which is tedious to copy out manually. This tool exports that text and those arrow points to a survey-style spreadsheet. That turns drawing callouts into usable field and office coordinates.',meta:'AutoCAD scripting · Civil 3D · Spreadsheet files'},
  {name:'Point Raw Description Leader',code:'DESC',label:'Survey description callouts',categories:['cad'],summary:'Survey points already carry raw descriptions, but turning each one into a readable callout leader by hand takes forever on large sets. This tool creates native multileader labels from those point descriptions automatically. That puts field descriptions on the drawing without retyping each callout.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'StretchLeader',code:'STRETCH',label:'Leader length cleanup',categories:['cad'],summary:'Multileader callouts often end up at uneven lengths, which makes a drawing look inconsistent and is tedious to fix one by one. This tool normalizes those leader lengths in batches without rebuilding the leaders or changing their text. That cleans up annotation appearance while keeping the wording intact.',meta:'AutoCAD scripting · AutoCAD'},
  {name:'LandXML Surface Combiner',code:'SURF',label:'Surface file combiner',categories:['cad','data'],summary:'Combining several TIN surfaces into one file while keeping the controlling footprint intact is awkward to do through manual Civil 3D steps. This tool merges those surfaces and retains the controlling surface outline. That produces one usable surface file for the next design or volume step.',meta:'Python · LandXML'},
  {name:'DXF Audit',code:'AUDIT',label:'Drawing content audit',categories:['cad','data'],summary:'Before running heavier automation, you need a clear inventory of what a drawing contains, and browsing layers and entities by hand is incomplete. This tool produces structured drawing, entity, and layer information from a DXF. That gives a reliable pre-check before other tools touch the file.',meta:'Python · DXF files'},
  {name:'Grid Label Audit',code:'LABEL',label:'Grid-and-label relationship audit',categories:['cad'],summary:'Missing, duplicate, or orphaned relationships between treatment grids and labels are hard to catch by eye before they cause reporting errors. This tool identifies those problems automatically. That catches label-to-grid mismatches before turnover or quantity work.',meta:'Python · DXF files'},
  {name:'LandXML Validator',code:'VALID',label:'Surface file validation',categories:['cad','data'],summary:'A generated LandXML surface can look fine until Civil 3D import fails on a structural or geometry problem. This tool checks those surface files for issues before import. That catches broken surface data early instead of during a failed CAD load.',meta:'Python · LandXML'},
  {name:'PNEZD Writer',code:'PNEZD',label:'Survey point file writer',categories:['data','field'],summary:'CAD and field tools expect survey points in a standard point-file format, and hand-building those files invites formatting mistakes. This tool writes standardized survey point files for downstream CAD and field workflows. That keeps point delivery consistent across office and field systems.',meta:'Python · Spreadsheet files · Survey data'},
  {name:'OCR Ticket Scanner',code:'SCAN',label:'Field ticket capture app',categories:['apps','field','data'],summary:'Field tickets still have to be photographed, read, approved, and logged, which usually means several disconnected steps. This app captures ticket images, queues OCR results for approval, and appends approved records to Excel Online. That closes the loop from field photo to tracked record with a human approval step.',meta:'Power Apps · OCR · SharePoint'},
  {name:'PDF Steamroller',code:'FLAT',label:'Difficult PDF flattener',categories:['utility'],summary:'Some AutoCAD-exported PDFs are huge, fragile, or hard for other systems to open reliably. This tool rasterizes and compresses those difficult PDFs into smaller, more dependable files. That makes awkward CAD exports usable for sharing and archiving.',meta:'Python · PDF · Image processing'},
  {name:'Photo Compressor',code:'PHOTO',label:'Field photo batch compression',categories:['utility','field'],summary:'Field photo folders get too large to share or archive, but compressing them carelessly can lose originals, metadata, or special formats. This tool batch-compresses photos while preserving originals, metadata, folders, multipage TIFFs, and animated GIFs. That shrinks field media without throwing away the source set.',meta:'Python · Image tools · Desktop app'},
  {name:'Viewpoint–DAR Time Audit',code:'TIME',label:'Timesheet-versus-DAR audit',categories:['reporting','data'],summary:'Comparing payroll timesheets with daily activity report hours by hand is slow and easy to miss exceptions. This tool compares employee timesheets with DAR personnel hours and produces an exception-focused workbook. That highlights labor mismatches instead of forcing a full manual line-by-line review.',meta:'Python · PDF · Excel'},
  {name:'Sign-In Sheet Cleanup',code:'SIGN',label:'Sign-in sheet print prep',categories:['data','reporting'],summary:'Sign-in forms often have the wrong number of rows for the day’s crew, which wastes paper or leaves no room for late arrivals. This tool resizes the form to the personnel list, adds blank rows, and prepares a one-page printout. That gets a clean sign-in sheet ready without manual row fiddling.',meta:'Excel macros · PowerShell'},
  {name:'Jobsite Field Map Builder',code:'MAP',label:'Jobsite visual field tracker',categories:['field','data'],summary:'Tracking where people, equipment, and work areas sit on a jobsite usually means rebuilding a visual board from CAD boundaries by hand. This tool builds an Excel visual tracker from those boundaries automatically. That gives the field team a living map of people, equipment, and areas.',meta:'Python · Excel · DXF'},
  {name:'Point Shape MLeader',code:'SHAPE',label:'Point-group shape callouts',categories:['cad'],summary:'Turning labeled point groups into closed shapes with callout leaders is repetitive drafting that still has to stay consistent. This tool converts those point groups into closed outlines and multileader callouts. That builds shape-based labels from point sets without redrawing each one.',meta:'CAD workflow',status:'In development'},
  {name:'WBSP V-Ditch Surface Generator',code:'DITCH',label:'WBSP V-ditch surface workflow',categories:['project','cad'],summary:'Repeating the same Civil 3D surface setup for the WBSP V-ditch design invites small setup differences from run to run. This tool generates that surface workflow in a repeatable sequence. That keeps the WBSP V-ditch design process consistent across updates.',meta:'Civil 3D · Surface design'},
  {name:'LRCP V-Ditch Design Workflow',code:'LRCP',label:'LRCP V-ditch grading workflow',categories:['project','cad'],summary:'The LRCP V-ditch design needs the same grading and surface steps each time, and doing them from memory is easy to drift. This tool applies that repeatable grading and surface workflow automatically. That keeps LRCP V-ditch design updates consistent.',meta:'Civil 3D · Grading'},
  {name:'WBSP Lime-Mixing LandXML Generator',code:'LIME',label:'WBSP lime-mixing surface export',categories:['project','cad','data'],summary:'Building LandXML surfaces for WBSP lime-mixing grid work from project inputs is a multi-step process that needs to stay consistent. This tool creates those surface files from the project inputs automatically. That prepares Civil 3D-ready surfaces for the lime-mixing grid workflow.',meta:'Python · LandXML · Civil 3D'},
  {name:'Landfill Grid MTEXT QA',code:'LFQA',label:'Landfill grid label QA',categories:['project','cad'],summary:'Landfill repair grids with missing or inconsistent text labels create QA risk before work moves forward. This tool checks those grid labels and geometry for gaps or inconsistencies. That catches landfill grid labeling problems before they reach the field.',meta:'AutoCAD · Quality check'},
  {name:'As-Built Drainage QA Highlighter',code:'DRAIN',label:'Drainage as-built QA highlight',categories:['project','cad','data'],summary:'Drainage as-built points that need engineering review are easy to bury in a large survey set. This tool highlights the point conditions that require review. That focuses engineers on the drainage issues that matter instead of scanning every point.',meta:'Civil 3D · Survey QA'},
  {name:'Civil 3D Drawing Health Check',code:'HEALTH',label:'Training drawing health check',categories:['project','cad'],summary:'Training drawings can hide setup problems that only show up when a lesson fails. This tool runs a repeatable diagnostic review of Civil 3D training drawings. That catches drawing-health issues before trainees hit them.',meta:'AutoCAD scripting · Civil 3D'},
  {name:'Civil 3D Training Drawing Builder',code:'BUILD',label:'Training drawing builder',categories:['project','cad'],summary:'Building the same Civil 3D training drawings over and over by hand wastes time and introduces setup differences. This tool builds those training drawings through a scripted setup workflow. That recreates consistent lesson files whenever they are needed.',meta:'PowerShell · Civil 3D'}
];

const excelAutomations = new Set([
  'Clifty Creek Master Workbook Updater',
  'MTEXT Workbook Sorter',
  'DAR Field Reporting App',
  'DAR Email-to-Workbook Pipeline',
  'QA/QC Elevation Workbooks',
  'Receipt Parser & Expense Grouper',
  'Phase Code Workbook Splitter',
  'Hermes DAR Controller',
  'Excel DAR RowHider',
  'OCR Ticket Scanner',
  'Viewpoint–DAR Time Audit',
  'Sign-In Sheet Cleanup',
  'Jobsite Field Map Builder'
]);
automations.forEach((automation) => {
  if (excelAutomations.has(automation.name) && !automation.categories.includes('excel')) automation.categories.push('excel');
});
const impactFiveAutomations = new Set([
  'Turnover Automation',
  'Trimble TSC7 Data Puller',
  'CAT VisionLink Fault Report Pipeline',
  'DAR Field Reporting App',
  'Load Count Log',
  'DAR Email-to-Workbook Pipeline',
  'QA/QC Elevation Workbooks',
  'ENTACT Civil 3D Assistant',
  'MasterFlow Cut / Fill Heat Map',
  'Hermes DAR Controller',
  'Viewpoint–DAR Time Audit',
  'Jobsite Field Map Builder',
  'WBSP V-Ditch Surface Generator',
  'LRCP V-Ditch Design Workflow',
  'WBSP Lime-Mixing LandXML Generator',
  'As-Built Drainage QA Highlighter'
]);
const impactOneAutomations = new Set([
  'Layer List',
  'Coordinate Picker',
  'AutoLISP Unloader',
  'XREF Reload All',
  'Site Map Draw-Order Cleanup',
  'Completed Grid QA Check'
]);
const impactFor = (automation) => {
  if (impactFiveAutomations.has(automation.name)) return 5;
  if (impactOneAutomations.has(automation.name)) return 1;
  const has = (category) => automation.categories.includes(category);
  if (has('apps') || (has('reporting') && has('data')) || (has('field') && has('data')) || (has('cad') && has('ai'))) return 4;
  if (['field','reporting','data','ai'].some(has)) return 3;
  return 2;
};
const impactDescriptions = {
  1: 'Small utility with targeted task-level impact',
  2: 'Focused productivity improvement',
  3: 'Recurring workflow improvement',
  4: 'Multi-step operational impact',
  5: 'Team-scale or business-critical impact'
};

const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const automationIdFor = (index) => `automation-${index + 1}`;
const featuredStories = [
  {name:'DAR Field Reporting App',focus:'Field reporting',story:'Brings personnel, equipment, quantities, notes, review, and delivery into one mobile field workflow.'},
  {name:'Turnover Automation',focus:'Field-to-office handoff',story:'Builds turnover fills and work-package layers, then connects survey points in one end-of-day run.'},
  {name:'QA/QC Elevation Workbooks',focus:'Quality control',story:'Compares survey elevations with design requirements and produces structured workbooks for focused review.'},
  {name:'ENTACT Civil 3D Assistant',focus:'Human-controlled AI',story:'Plans repeatable drafting actions locally, requires confirmation, and preserves an auditable execution record.'},
  {name:'MasterFlow Cut / Fill Heat Map',focus:'Civil 3D production',story:'Turns several surface-import, volume, boundary, and styling steps into one controlled heat-map workflow.'},
  {name:'Viewpoint–DAR Time Audit',focus:'Project controls',story:'Compares payroll timesheets with daily-report hours and produces an exception-focused workbook.'}
];
const featuredGrid = document.querySelector('[data-featured-automations]');
if (featuredGrid) {
  featuredGrid.innerHTML = featuredStories.map((featured, rank) => {
    const index = automations.findIndex((automation) => automation.name === featured.name);
    if (index < 0) return '';
    const automation = automations[index];
    const impact = impactFor(automation);
    return `<article class="automation-featured-card">
      <div class="featured-automation-top"><span>${String(rank + 1).padStart(2, '0')}</span><p>${escapeHtml(featured.focus)}</p></div>
      <h3>${escapeHtml(automation.name)}</h3><p>${escapeHtml(featured.story)}</p>
      <div class="featured-automation-footer"><span>Impact ${impact}/5</span><a href="#${automationIdFor(index)}">Find in catalog ↓</a></div>
    </article>`;
  }).join('');
}
const grid = document.querySelector('[data-automation-grid]');
if (grid) {
  grid.innerHTML = automations.map((automation, index) => {
    const number = String(index + 1).padStart(2, '0');
    const search = [automation.name, automation.label, automation.summary, automation.meta, ...automation.categories].join(' ').toLowerCase();
    const action = '<span class="automation-private">Private automation</span>';
    const status = automation.status ? `<span class="automation-status">${escapeHtml(automation.status)}</span>` : '';
    const impact = impactFor(automation);
    const impactBars = Array.from({length:5}, (_, index) => `<i class="${index < impact ? 'is-filled' : ''}"></i>`).join('');
    const impactBadge = `<span class="impact-indicator impact-${impact}" title="${escapeHtml(impactDescriptions[impact])}" aria-label="Impact ${impact} out of 5"><span>Impact</span><span class="impact-meter" aria-hidden="true">${impactBars}</span><b>${impact}/5</b></span>`;
    return `<article class="automation-card" id="${automationIdFor(index)}" data-automation data-category="${automation.categories.join(' ')}" data-search="${escapeHtml(search)}">
      <div class="automation-visual"><span class="automation-code">JH / ${number}</span><strong>${escapeHtml(automation.code)}</strong><i></i></div>
      <div class="automation-content"><div class="automation-heading"><p class="automation-category">${escapeHtml(automation.label)}</p><div class="automation-signals">${impactBadge}${status}</div></div><h2>${escapeHtml(automation.name)}</h2><p>${escapeHtml(automation.summary)}</p><div class="automation-footer"><span>${escapeHtml(automation.meta)}</span>${action}</div></div>
    </article>`;
  }).join('');
}
